[project]
name = "langchain-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastembed>=0.2.7",
    "ipython>=9.9.0",
    "langchain>=1.2.1",
    "langchain-anthropic>=1.3.1",
    "langchain-classic>=1.0.1",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.1.3",
    "langchain-google-vertexai>=3.2.1",
    "langchain-openai>=1.1.7",
    "langchain-qdrant>=1.1.0",
    "lxml>=6.0.2",
    "matplotlib-inline>=0.2.1",
    "pillow>=12.1.0",
    "pymupdf>=1.26.7",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.16.2",
    "unstructured-client>=0.42.6",
    "unstructured[all-docs]>=0.18.27",
]
